### ISSUE TITLE
Events - scaling. rpcServer dispatch is too slow

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#103]
See in worker: https://github.com/vistadataproject/nodeVISTA/blob/master/rpcServer/rpcQWorker.js#L249

Issue: RPC events sent in same process (server) that sends incoming traffic to worker

Need to examine patterns for web socket handling in worker/multi-process setups.

**Comment by mfuroyama** [comment]
### Notes to Self
I don't know if there are common patterns that match what we're doing, but I'd like to take a running swag at moving the MVDM Client to a separate child process, and dispatch RPC and MVDM events via IPC.

It makes logical sense that the web server exist as a separate process as its own entity and manages its own resources (i.e. websockets). Plus, thanks to the event-based architecture implemented via the EventManager, it should be pretty simple to make a clean cut to partition off the MVDM client functionality. 

We'll insert an Adapter between the EventManager and the MVDM Client to use the IPC pipes to relay events back and forth. Events would still bubble up from the EWD worker child processes, but then would be routed back to the MVDM Client triggered by events; we wouldn't need to change the existing rpcServer code all that much. Basically, the rpcServer would become a router for these messages.

One note: we'd also have to manage the communication from the MVDM Client to the server process (MVDM Management setting of `isRPCLocked`) but that's easy with the client process API. Most of that can happen behind the scenes as well.
