### ISSUE TITLE
Incorporate Dr Richards demo instruction improvements to demo wiki

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#111]
http://vistadataproject.info/demo/ is demo wiki

**Comment by rafael5** [comment]
### In file "nv.sh" in user's root dirctory  on host (i.e. in  ~/nv.sh)
clear
figlet  nodeVISTA
echo '      Website: http://vistadataproject.info '
echo '     Node.js / Master Data Model-Driven VISTA  '
echo ' -----------------------------------------------------'
echo ' Server Status:       nv- start | stop | status'
echo ' Server Access:       nv- ssh | ssh-web  (vdp/vdp)'
echo ' Web Clients:         nv-vdm-browser | nv-manager'
echo ' -----------------------------------------------------'


### In file ".profile" in user's root directory  on host (i.e.  ~/.profile )

# nodeVISTA
#-------------------------------------------------------------------------------------
alias nv='clear; sh ~/nv.sh'
# Server Status
alias nv-start='cd ~/vagrant/nodeVISTA/setup; vagrant reload'
alias nv-stop='cd ~/vagrant/nodeVISTA/setup; vagrant halt'
alias nv-status='cd ~vagrant/nodeVISTA/setup; vagrant status'
# Server Access
alias nv-ssh-web='echo "nodeVISTA ssh user/pass: vdp/vdp"; open https://10.2.2.100:4200/'
alias nv-ssh='echo "nodeVISTA ssh user/pass: vdp/vdp"; ssh vdp@10.2.2.100'
# web Clients
alias nv-vdm-browser='open http://10.2.2.100:9000'
alias nv-manager='open http://10.2.2.100:9020/#rpcCounts'

**Comment by conorcaregraf** [comment]
Add to demo instruction install last step ...

put into profile

```text
#/ Server Status
alias nv-reload='cd ~/vagrant/nodeVISTA/setup; vagrant reload; nv-status'
alias nv-halt='cd ~/vagrant/nodeVISTA/setup; vagrant halt; nv-status'
alias nv-status='cd ~/vagrant/nodeVISTA/setup; nv; vagrant status'

#/ Server Access
#/ Direct terminal:
alias nv-ssh='echo "nodeVISTA ssh user/pass: vdp/vdp"; ssh vdp@10.2.2.100'

```

**Comment by mfuroyama** [comment]
Updated the project demo website to incorporate these suggestions.

Also, while I was in there, updated the screenshots to reflect the current state of the UI software.
