### ISSUE TITLE
user directory /home/vdp/dev required for vagrant build to syncfolders

### ISSUE THREAD

**Issue by bciv** [vistadataproject/nodeVISTA#119]
nodeVistA - Ubuntu: /home/vdp/dev => /Users/myusername/github
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

id -u vdp

The error output from the command was:

id: ‘vdp’: no such user

**Comment by bciv** [comment]
Commented out /home/vdp user from Vagrantfile and was able to build.  Maybe that wasn't a good idea?

54 #  #share VDM development directory
55 #  config.vm.synced_folder "../../", "/home/vdp/dev", owner: "vdp", group: "vdp"

**Comment by mfuroyama** [comment]
Hey @bciv! If I'm understanding your issue correctly, you may have caught the repo in a bad state. The Vagrantfile was in a state of flux a few days ago.  However, the current iteration of the Vagrantfile in the setup pulls down a pre-built **nodeVISTA** VM image that should already have a **vdp** user setup and should already contain the `/home/vdp/dev` mount point.

We leave a handful of directives in the Vagrantfile, commented out, as reminders for when we need to generate a new VM image from scratch.

I'd say, try doing a fresh fetch/pull, clear out any cached **nodeVISTA** Vagrant VMs (`vagrant box remove --all`), destroy your existing **nodeVISTA** Vagrant VM and try re-upping the VM.

Mentioning @conorcaregraf for tracking...

**Comment by mfuroyama** [comment]
I'm going to assign this issue to myself so that I don't drop the ball on it, and will close it pending feedback from @bciv, @conorcaregraf and/or others.

**Comment by bciv** [comment]
Thank you.   I will do a new pull and try again.  


Sent from my Samsung device

-------- Original message --------

**Comment by mfuroyama** [comment]
Hey @bciv! Hope you had a great Easter! Just following up on this issue: were you able to determine whether or not a fresh pull of the repository resolved your issue? Unless I hear otherwise, I'm going to close this issue.

On a related note, just wanted to say thanks for your interest in our open source project! Out of curiosity, are there one or more particular aspects of the project that are of unique interest to you? If so, I might be able to guide you to one of our several related repositories. Thanks again!

**Comment by bciv** [comment]
Thanks!

The fresh pull resolved the issue.

Read and write-back to VistA and seeing different implementations of building VistA are interesting to me.
