### ISSUE TITLE
Change nodeVISTA welcome screen

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#123]
![e8618586-ef77-11e6-8973-f87c337738dd](https://cloud.githubusercontent.com/assets/1831390/24785567/f87c16de-1b0f-11e7-9bcb-396d884a89f7.png)

**Comment by mfuroyama** [comment]
### Notes
* The intro message is a FREE TEXT field in the System Parameters (8989.3) file type (`intro_message`, location `INTRO;0`)
* The value should be a string, with newlines indicated with the `\r` carriage return character
* The message can be any size/length, but it should probably fit within the default intro window size, which appears to be 80 x 23

### Non-Clinical VDM
The value can be set using the following code:
```Javascript
const text = 'Your spiffy new intro message`;
VDM.update({ id: '8989_3-1', type: 'Kernel_System_Parameters-8989_3', intro_message: text });
```

**Comment by mfuroyama** [comment]
Linked this issue to one generated in **nonClinicalRPCs**: https://github.com/vistadataproject/nonClinicalRPCs/issues/260.  Prototyping and testing should occur in **nonClinicalRPCs**, then moved over to **nodeVISTA** when finished.
