### ISSUE TITLE
Fix Mgmt Screen Pie with Unstructured Read etc

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#126]
The third pie in the mgmt screen talks of "unstructured" READ etc. we don't use those terms any more so let's remove em ...

![forsteveissue-fixconfigfilesoallnc cetc](https://user-images.githubusercontent.com/1831390/27877557-faff87d2-616f-11e7-956a-3a2e8fa698a3.png)

**Comment by sbruno81** [comment]
We'll need to cut a new image of nodeVISTA to see changes in deployment
