### ISSUE TITLE
Try CPRS against nodeVISTA

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#19]
__**TODO: TRANSFER ALL TO DEMO WIKI ** ie/ part of running demo.__ in particular anything about getting vitals separately (or is this all taken care of in the VISTA CPRS?)

_Do you have showrpcs in you shortcut to CPRS and does you test user have XU keys? If so, look under help in CPRS for the RPCs called._

...

https://github.com/OSEHRA/VistA/blob/master/Documentation/Install/Vagrant.rst#cprs-and-other-gui-programs <--- key and points off to another doc with latest CPRS

and VA page with manuals: http://wiki.osehra.org/display/VAF/Computerized+Patient+Record+System+(CPRS)+-+VA+VistA+GUI

**UPDATE**: page referenced from Vagrant Instructions is wrong - go to latest FOIA - https://www.osehra.org/comment/2026#comment-2026 (found on hardhats)

**Context**: they've changed the cypher - https://www.osehra.org/blog/vista-m-and-delphi-guis-problem

**MORE**:
- Needed to copy DLL into sys32 Windows (and did for 64bit too) 
- still getting **WSAEADDRNOTAVAIL** problem
  - found this on resetting VM props ala first instruction  https://www.osehra.org/wiki/cprs-connection-vm)
    - in VM with ifconfig saw _inet addr:10.0.2.15_ , REM: 9430 is port for RPC Broker.

**Manuals**:
- http://www.va.gov/vdl/documents/Clinical/Comp_Patient_Recrd_Sys_(CPRS)/cprsguitm.pdf
- [old astronaut video](https://www.youtube.com/watch?v=mmVfy6pbvI4)

**Comment by conorcaregraf** [comment]
## Progress in Windows 10

__Downsides (see below)__: 
  * need to hack the server's CPRS version so the FOIA CPRS of OSEHRA works.
  * perhaps related - when click on vital in the opening chart, told .dll is missing.

Shortcut to CPRS - set S (Server) and P (port). S points to n/w given from Vagrant Ubuntu using _ifconfig_

![screen shot 2016-02-16 at 4 23 55 pm](https://cloud.githubusercontent.com/assets/1831390/13095841/ca7c8922-d4c9-11e5-8cdd-d1334ad56c1d.png)

Ready to login ...

![screen shot 2016-02-16 at 3 47 12 pm](https://cloud.githubusercontent.com/assets/1831390/13095816/906f6588-d4c9-11e5-9307-ebba085161d3.png)

using: _fakedoc!_ and _@#$_

But told CPRS is old ...

![screen shot 2016-02-16 at 3 59 00 pm](https://cloud.githubusercontent.com/assets/1831390/13095811/84016616-d4c9-11e5-99e4-2abb7c601c1c.png)


Need to change Server side (cheat!) to make this (old) CPRS work ...

![screen shot 2016-02-16 at 4 12 06 pm](https://cloud.githubusercontent.com/assets/1831390/13095800/776ac064-d4c9-11e5-9436-fa5a7c519bb5.png)


Patient Selection (chose David Carter as putting data there for now):

![screen shot 2016-02-16 at 4 13 19 pm](https://cloud.githubusercontent.com/assets/1831390/13095794/662ae87e-d4c9-11e5-8cd2-6af5ea2f9049.png)


Vital (entered with VDM create):

![screen shot 2016-02-16 at 4 14 24 pm](https://cloud.githubusercontent.com/assets/1831390/13095790/538e7e7e-d4c9-11e5-94f4-c415b4a639ae.png)


Missing DLL in Vital ...

![screen shot 2016-02-16 at 4 20 14 pm](https://cloud.githubusercontent.com/assets/1831390/13095774/416eec38-d4c9-11e5-8f44-7097637a9720.png)

**Comment by whitten** [comment]
Allergy and problems use the main CPRSChart.exe

 Vitals LITE expects that DLL to be in C:\program files\vista\common files\  as I recall.

you may also need the memory management dll as well.

**Comment by conorcaregraf** [comment]
thanks again Dave. 

Chris wrote 

> Try using the vitals lite dll from the functional testing guis download. the vitals lite component doesn't get updated very often and i will assume it works correctly: http://osehra.org/sites/default/files/functionaltestingguis.zip

but memory too eh ... ok.

**Comment by whitten** [comment]
The name is  borlndmm.dll it converts internal Borland style pointers to wide MS Windows pointers.

**Comment by conorcaregraf** [comment]
__BG__: VA has add ons for CPRS for various functions

  1. Vitals is a key one we test with
  2. [CAPRI](http://www.va.gov/vdl/documents/Financial_Admin/CAPRI/capri_gui_isg.pdf) for finance/admin ... look to its RPCs and coverage

Need complete list from VA to fully scope RPCs we need to cover.
