### ISSUE TITLE
OSEHRA:  Establish and *maintain* vagrant installation of gtm/ cache / node / vista / cprs with sample data

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTA#28]
OSEHRA has started a Github-based vagrant installation, but does not appear to be maintaining it.

https://www.osehra.org/content/how-setup-osehra-vista-development-virtual-machine-vm-0

=> Have this be a core task in osehra 2016-2017 task order

**Comment by whitten** [comment]
I think the WorldVistA VistA for Education edition includes some sample patients and Mike Stark's patient loader from Excel program.  The dEWDrop edition has the SMART patients as well, as I recall.
