### ISSUE TITLE
OSEHRA - source KIDS and M source control on Github

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTA#29]
OSEHRA started this  VISTA cleanup work in 2011, but never completed it:

https://www.osehra.org/wiki/osehra-system-architecture

* Source KIDS M  code source control for Github
* De-conflict duplicate namespaces and duplicate modules
* Add master list of Namespaces and Numberspaces, based on VA internal feedback.
* Investigate modules without documentation
* Harmonize ICRs (aka DBIAs) across SA, based on VA internal documentation
* Add missing APIs, RPCs and Component Diagrams
* Add patchs to module-diagrams and map patches-to-modules
* Map Namespaces-to-modules and visa-versa
* Incorporate Xindex mapping of modules-to-routines and modules-to-data files

**Comment by conorcaregraf** [comment]
dup
