### ISSUE TITLE
EWD (Tracking)

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#34]
__Background__:

VISTA has its own remote service protocol and infrastructure, the "RPC Broker". This allows remote clients of any language (JS, Java, C#, Pascal ...) to login to VISTA and invoke one of 3500 RPCs. 

Rather than use the MUMPS implemented broker, there is a move to implement the broker in Javascript running inside Node.js. The main example of this is another EWD module.

__We will try EWD in parts__: in four servers, _rpcJobServer.js_ (express interface), _fmqlJobServer_, _mvdmJobServer_ and in a __rpcBrokerServer__

__Directory__: [interfaces](https://github.com/vistadataproject/nodeVISTA/tree/master/interfaces)

__Roll of this Issue__: track issues/insights into using EWD.

**Comment by whitten** [comment]
Have you looked at RobTweeds VistA RPC Broker at
https://github.com/robtweed/ewd-qoper8-vistarpc/blob/master/lib/vistarpc.js
(part of https://github.com/robtweed/ewd-qoper8-vistarpc/tree/master/lib )
and
https://github.com/robtweed/ewd-vista-rpc/blob/master/lib/ewd-vista-rpc.js

I don't know the differences, just there are a lot of programs out there that purport to
being Javascript based RPC Brokers.

**Comment by conorcaregraf** [comment]
## EWD Broker

https://github.com/robtweed/ewd-qoper8-vistarpc

Questions:
  * does this fit neatly into nodeVISTA's setup (with express/auth/logging/ewd job queue?)
    * ie/ can it be setup as just another worker pool (ala FMQL) 

To try:
  * try as is: ie/ in separate ewdBroker prototype.

**Comment by conorcaregraf** [comment]
## eHMP broker.js

See example - 

```text

var context = 'OR CPRS GUI CHART'; ... BEST CONTEXT

var configuration = {
    context: 'HMP UI CONTEXT',
    host: '10.2.2.101',
    port: 9210,
    accessCode: 'pu1234',
    verifyCode: 'pu1234!!',
    localIP: '10.2.2.1',
    localAddress: 'localhost'
};

VistaJS.callRpc(logger, configuration, 'ORWU USERINFO', printResult);

```

Do latest v1.3.

__Background__: adds icing to RPC testing. Can't just invoke (directly) locally. Want to check any additional absence/presence and value bounds checking done by Broker.

**Comment by conorcaregraf** [comment]
## From Rob from our feedback ... 

lot's of settings ...

```text
... the latest releases of ewd-session and ewd-qoper8-vistarpc.

The latter also includes some subtle enhancements arising from its use in eHMP:

- you can now optionally instruct the login API to return the DUZ value in its response.  Since exposing a DUZ is not really a good idea, the default is not to return it, and to maintain security, the over-ride is done in the configuration settings in your master process startup JS file.  Just add these lines inside the q.on('started', function() {...} callback

  this.userDefined = {
    returnDUZ: true
  };

- you can now opt to have the raw RPC value returned (instead of a conversion of ^ pieced strings to an array) by adding to the URL the name/value pair:
      
       format=raw

- you can now opt to have GLOBAL ARRAY types return their response in the same request by adding to the URL the name/value pair:

      returnGlobalArray=true

It also fixes that GT.M login error - this was because David chose, in Nodem, to automatically detect and convert numeric values returned from GT.M, whereas cache.node leaves them as strings.  So a failed login was detected by duz === '0'  which, in GT.M would fail.  So now it checks duz.toString() === '0' to normalise the behaviour.

The new builds are on Github and NPM

------

Oh you can also define the context by adding the name/value pair to the URL:

  context=CONTEXT%20NAME

the context name must be URL-escaped
```

**Comment by conorcaregraf** [comment]
## TODO: run vista.js module

... fill in details on passing in login credentials ie/ JUST DO SIMPLE HELLO WORLD FIRST.

**Comment by conorcaregraf** [comment]
## Issues x 2:

Two manual changes to EWD to make the client work:

__1. Comment out a line in node_modules/ewd-qoper8-gtm/lib/setEnvironment.js__

... delete the following line as '/usr/lib/fis-gtm' is NOT in our OSEHRA VISTA system

```text
    // var gtmver2 = fs.readdirSync('/usr/lib/fis-gtm')[0];
```

__2. node_modules/ewd-qoper8-vistarpc/lib/proto/runRPC.js__

ADD logic to set result type to GLOBAL ARRAY if no type is defined. "GLOBAL ARRAY" leaves results.type undefined.

```text

  else {
    var resultsNode = gloRef.$('result');
    var results = resultsNode.getDocument(true);

    if (results.type === undefined) { 
        results.type = "GLOBAL ARRAY";
        console.log("WARNING: no results type set for %s", rpcName);
    }

```

and question: why treat GLOBAL ARRAY so differently ie/ embed in a session and take out of there instead of just reading the passed in TMP as is done for SINGLE VALUE and ARRAY?

**Comment by whitten** [comment]
Many times, RPC calls that are type GLOBAL ARRAY return their results in a "glocal" i.e. a global variable indexed by $JOB.  These arrays cannot be found by a call back to VistA to retrieve them
because the $JOB value changes each time a process is run on the M side to service a request.
So the data is copied to the Session Global because that is the closest analogue to a glocal.

**Comment by whitten** [comment]
> So why treat GLOBAL ARRAY differently? Just merge the contents of the global array into the
> TMP  passed in. Why put it into the session?
> 
Well, actually we did try to merge the contents of the global array into the TMP passed in.
And promptly got an error that we were trying to copy a global into a subtree of itself.

The Javascript lines that use ^TMP( $J  ) as a result run into the problem that some RPCs
return their results in ^TMP($J) . I guess I need to put that in as a bug report to Rob.

  var status = this.db.function({
    function: "RPCEXECUTE^ewdVistARPC", 
    arguments: ['^TMP(' + process.pid + ')', id, documentName]
  });

this should probably be:

  var status = this.db.function({
    function: "RPCEXECUTE^ewdVistARPC", 
    arguments: ['^TMP("zewd",' + process.pid + ')', id, documentName]
  });

(i.e. to use a namespaced subscript to guarantee no over-writing )
