### ISSUE TITLE
EWD vs KUE (subset of EWD work)

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#35]
__TODO__: [move to wiki](https://github.com/vistadataproject/VDM/wiki/Job-Server)

__Background__: EWD is (now) a set of components to ease the development of Node.js based servers for MUMPS-based systems like VISTA. This queue - with in-memory and in database options - is one key component, one that works like Kue and its ilk.

__Obvious Advantage__: as it uses Cache or GT.M and not Redis, there is no separate DB. Redis may not be approved (right now) by the VA.

__Open Question__: ease of use, performance etc.

__TODO__: try in place of Kue and give #'s.

**Comment by conorcaregraf** [comment]
## And go beyond (later ...)

```text
So just to summarise the components I've created that you should be looking at for your project:

- ewd-qoper8   This is the core queue mechanism that everything else uses to allow you to work sanely in synchronous logic with the VistA data
- ewd-qoper8-express  - adds Express-specific functionality, eg standard message structure from the Express req object, and a handy message handler and router
- ewd-qoper8-dbq  - if you want a database queue instead of the memory-based one provided by default in ewd-qoper8

- ewd-qoper8-cache   and ewd-qoper8-gtm   for connecting ewd-qoper8 worker processes to Cache (via cache.node) and GT.M (via nodem) 

- ewd-document-store (installed automatically by ewd-qoper8-cache and ewd-qoper8-gtm)  - projects Mumps globals as persistent JS objects and document database

- ewd-session  - everything you need for session management using ewd-document-store

This stack will save you a huge amount of time and farting about with other stuff

Every component has a Github repo with documentation and worked examples.
```

**Comment by pcchanghawaii** [comment]
Thanks, Conor

I have been reading EWD documents. It looks like no clustering function
provided there so each node will have its own queue. Will do some coding
today.

Pei

**Comment by conorcaregraf** [comment]
## Vs Kue

prelim ...

```text
Here's the performance test for the in-memory EWD. 

1. ewd in-memory queue
command: nperf -c 200 -n 1000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1
{ statuses: { '200': 1000 },
  min: 386,
  max: 4050,
  avg: 2645.895,
  count: 1000,
  rate: 68.87526689165921,
  start: 1458539944777,
  total_time: 14519 }

2. ewd in-memory queue
command: nperf -c 200 -n 3000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1 
failed. socket hang up
processed the first 1600 only.



3. kue with redis queue
command: nperf -c 200 -n 1000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1
{ statuses: { '200': 1000 },
  min: 142,
  max: 2355,
  avg: 1187.652999999999,
  count: 1000,
  rate: 154.53562046051613,
  start: 1458540820125,
  total_time: 6471 }

  4. kue with redis queue
  command: nperf -c 200 -n 3000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1
  { statuses: { '0': 1006, '200': 1994 },
  min: 97,
  max: 44021,
  avg: 4842.387999999995,
  count: 3000,
  rate: 37.08556876900635,
  start: 1458540867355,
  total_time: 80895 }
```

**Comment by conorcaregraf** [comment]
## Environment setup for OSEHRA VISTA

... TODO ... put in the env settings needed to make this work for OSEHRA VISTA's (VDP User's) GTM setup.

**Comment by whitten** [comment]
When you test, it would be interesting to know to what degree the disk is a controlling factor.
GT.M supports a MM type global which is a memory mapped global.
If we mapped all the globals in VistA as MM type globals, it would remove the
need to hit the disk to search/change/update. (of course if the system crashes...)

**Comment by conorcaregraf** [comment]
## Performance test ...

```text

nperf -c 200 -n 5000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1

{ statuses: { '200': 5000 },

  min: 417,

  max: 4100,

  avg: 2793.914600000004,

  count: 5000,

  rate: 70.26616824531325,

  start: 1458712030997,

  total_time: 71158 }

```

It seems to be the best so far ... it seems to be more stable than kue with Redis. It can handle all of the 5000 requests with 70 request/second. The Kue with Redis can't handle all of 5000 requests correctly. Kue only handles 4000 out of 5000 successfully.

Caveat: our virtual box is not a real cluster environment so these tests do not tell us the performance difference in the real cluster server.

## Architecture:

The architecture of the two are different also. Kue with Redis has only one global queue and each worker receives request from express and put the job into the global queue. Each worker also reads job from the queue and process it. 

EWD one is a bit different. Each worker works in a silo mode because it doesn't have a global queue. Instead each worker has its own queue.

## Dave point on Globals in memory (see above)

Is this a factor/possibility ie/ seemless in memory or on disk - same code, just a different setting?

**Comment by pcchanghawaii** [comment]
|EWD in Database |EWD in memory Queue|KUE with Redis Queue
|-------------------------|--------------------------------|-------------------------------|
||command: nperf -c 200 -n 1000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1 <br> { statuses: { '200': 1000 },<br>  min: 386,<br>  max: 4050,<br>  avg: 2645.90,<br>  count: 1000,<br>  rate: 68.88,<br>  start: 1458539944777,<br>  total_time: 14519ms }|command: nperf -c 200 -n 1000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1<br>{ statuses: { '200': 1000 },<br>  min: 142,<br>  max: 2355,<br>  avg: 1187.65,<br>  count: 1000,<br>  rate: 154.54,<br>  start: 1458540820125,<br>  total_time: 6471ms }
|command: <br>nperf -c 200 -n 5000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1<br> { statuses: { '200': 5000 },<br>  min: 417,<br>  max: 4100,<br>  avg: 2793.91,<br>  count: 5000,<br>  rate: 70.26616824531325,<br>  start: 1458712030997,<br>  total_time: 71158ms }|command: nperf -c 200 -n 3000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1 <br>failed. socket hang up<br>processed the first 1600 only.| command: nperf -c 200 -n 3000 http://localhost:9000/fmqlEP?fmql=DESCRIBE%202-1<br>  { statuses: { '0': 1006, '200': 1994 },<br>  min: 97,<br>  max: 44021,<br>  avg: 4842.39,<br>  count: 3000,<br>  rate: 37.09,<br>  start: 1458540867355,<br>  total_time: 80895ms }|

**Comment by conorcaregraf** [comment]
More BG from Rob ...

  * Chris Munt (author of cache.node) has demonstrated using a C++ client that cache.node is capable of faster than native Mumps code access to globals (which is quite extra-ordinary) - but the Node.js client is severely limited by Google Chrome V8 API bottlenecks.  

  * The performance of GT.M is going to be VERY much slower than cache.node.  That's because every database access requires Mumps indirection.  With GT.M I don't know how much will be gained with memory mapped globals for that reason. ... [needs] work on a data access layer for GT.M to create a high-performance, low-level interface directly into the global database engine.  

   * global access using Mumps code is capable of over 1 million global sets per second, even on modest hardware.  If we could get that speed of access using JavaScript, both GT.M and Cache would leave every other database on the planet in a cloud of dust.

**Comment by conorcaregraf** [comment]
From Rob on Cluster/EWD ...

>The architecture is not as you describe.  The master process adds incoming requests to a single queue 
> (either in-memory or to a global that acts as a queue).  The master process then checks to find the first
 > available worker and assigns the first member of the queue to that worker.  When working with a 
> database queue, the master sends a signal to the worker, and, on receipt, the worker pulls its assigned 
> record from the database queue.  All workers in the pool are fed from the one database queue.

... that EWD "queue" is really a cluster/kue combo?

**Comment by conorcaregraf** [comment]
More: see "fix" in _nodeVISTA/interfaces_
