### ISSUE TITLE
Why is JobServer slower than old RPC Broker?

### ISSUE THREAD

**Issue by pcchanghawaii** [vistadataproject/nodeVISTA#53]
I added the performance tests to both rpcJobServerClientAllergies.js and rpcBrokerAllergies.js. 
I compared the difference by reading the allergies 100 times. The performance difference is huge:
rpcBrokerAllergies takes 4444 milliseconds, but the jobServer takes 
106512 milliseconds. It means job server is 24 times slower. 

we're using GT.M and not Cache. That we need to test with Cache and will do so later. node for GT.M is known to be slower.

**Comment by conorcaregraf** [comment]
Note - will revisit Pei's initial results when rpcBrokerJobServer exists. Then we'll have two RPC Brokers.
