### ISSUE TITLE
Begin Javascript Test framework work against NodeVistA

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#6]
Unit Tests: _jasmine_ or _mocha_

  * http://thejsguy.com/2015/01/12/jasmine-vs-mocha-chai-and-sinon.html - comes out for Jasmine
  * http://www.techtalkdc.com/which-javascript-test-library-should-you-use-qunit-vs-jasmine-vs-mocha/
  * http://www.elijahmanor.com/unit-test-like-a-secret-agent-with-sinon-js/

Will probably do jasmine.

A really nice node.js expect ... module: https://github.com/moll/js-must

_jasmine_ supports Python too: https://github.com/jasmine/jasmine-py

**Comment by whitten** [comment]
So, did you decide to use Jasmine or Mocha?
I believe the OSEHRA folks have a Javascript testing framework.
Have you talked to them (certification work group that meets 1pm EST on Tues ?)
What are your goals for the testing framework?
