### ISSUE TITLE
Vagrant 1.1

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#86]
From December Vagrant, do small fixes to remove error reports and automate all aspects. Needs to be "bomb proof" and suitable for client developers as well as us. 

- [x] VM name shorten 
- [x] Use explicit (working) version of nodem
- [x] vitals set up works __CONOR__
- [x] rpcServer auto start (no need to vagrant ssh to use demo
- [x] osehra -> nodeVISTA in directories and elsewhere (feature/not bug)
- [x] users (robert) signature setting (doesn't work now) __Conor__
- [x] users have verify that doesn't expire so don't have to reset - what is the PARAMETER?
- [x] restart old broker 
- [x] UTC Time set for Ubuntu in Vagrant - do from time setting of local user
- [x] capri setup works (TEST IF FIXED)
- [x] CPRS version problem - VISTA now at .75 but we are using CPRS .69

Fixed Vagrant setup:
- [x] fixed vagrant box - "AINA-like" ... vagrant file has inline and comment out

Make Release
- [x] put "Vagrant box" on linode 
- [x] put CPRS version that works with box on Linode with DLL
- [x] release note on MVDM git - in the main README and pt to demo for how to run things
- [x] demo wiki updates
  - [x] download from linode
  - [x] how to setup CPRS (OSEHRA install, override exe, DLL)
- [x] Hawaii runs through whole setup (go to Demo and go from there ... mail mike to get done)
- [x] (for release in general) -- tag 1.1 post Hawaii ok

**Comment by conorcaregraf** [comment]
VERIFY: 

```text
VCHG() ;Check if the Verify code needs to be changed
 I $D(DUZ("ASH")) Q 0 ;p403
 D:'$D(XUSER) USER^XUS(DUZ)
 Q:'$L($P(XUSER(1),U,2)) 1 ;Null VC
 I $$BROKER^XWBLIB Q:$P(XUSER(0),U,8)=1 0 ;VC never expires, only for BROKER
 Q (XUSER(1)+$P(XOPT,U,15))'>$H ;Time to change
 ;
```

![screen shot 2016-12-23 at 2 46 59 pm](https://cloud.githubusercontent.com/assets/1831390/21464110/1aed3650-c929-11e6-880c-350f879181e6.png)

...

![screen shot 2016-12-23 at 2 47 11 pm](https://cloud.githubusercontent.com/assets/1831390/21464113/293d8e58-c929-11e6-885f-7b39c9c19a4a.png)

**Comment by conorcaregraf** [comment]
RR ...

```text
any chance the VM name can be shortened and the meaningless numbers dropped?

from: "setup_nodeVistA-Ubuntu_1482814426155_59636"

to just:   "nodeVISTA"
```

**Comment by sbruno81** [comment]
VM name has been shortened to "nodeVISTA"

**Comment by rafael5** [comment]
=> Update vagrant script to incorporate latest version of Node/M, updated 2017-01-08

Latest version of NodeM for GTM is available here:
https://github.com/dlwicksell/nodem

**Comment by conorcaregraf** [comment]
## Changing 'OSEHRA' to 'nodeVISTA'

OSEHRA uses its own name ($instance) every where. Move back to FOIA and use nodeVISTA as directory etc names.

ie/ home/nodeVISTA and nodeVISTA> etc.

Settings to change:
1. $basedir (set to /home/osehra) 
   - used in importVistA.sh in GTM
   - reset in importVistA.sh
2. $instance
   - basedir=/home/$instance set in importVistA.sh
   - others in here use $instance for PROMPT etc
   - #set variables instance="osehra" <--- setup.sh sets this
   - ... but there are fixed 'osehra' in places and need to remove

## GTM logging "issue"

and copy of nodeVISTA in /usr/local/src

GTM stores process logs (.mjo etc) in working directory (ex/ _ZTM0.mjo_ if job spawner). Issue that may not have permission to write to startup directory.

Showed up during restart of taskman by vdp user ...

> %GTM-I-TEXT, Job error in creating STDOUT

Note found that _GT.M allows you to explicitly specify the locations of the .mje and .mjo files for STDERR and STDOUT_ but how?

For now work around was to re-install nodeVISTA in /usr/local/src and run gtm using scripts there BUT not ideal. Better to fit into flow of start of install script.

TODO: revisit permissions issues and remove second nodeVISTA install.

**Comment by conorcaregraf** [comment]
DONE.
